--
-- SVN INFORMATION:::
-- SVN Signature::::::::: $Id:tables.sql 23 2008-04-18 04:25:47Z crazedsanity $
-- Last Committted Date:: $Date:2008-04-17 23:25:47 -0500 (Thu, 17 Apr 2008) $
-- Last Committed Path::: $HeadURL:https://cs-battletrack.svn.sourceforge.net/svnroot/cs-battletrack/trunk/docs/sql/tables.sql $
--  

--
-- Contains a list of campaigns.
--
CREATE TABLE csbt_campaign_table (
	campaign_id serial NOT NULL PRIMARY KEY,
	campaign_name varchar(128) NOT NULL UNIQUE,	
	owner_uid integer NOT NULL REFERENCES cs_authentication_table(uid),
	create_date timestamp NOT NULL DEFAULT NOW(),
	is_active bool NOT NULL DEFAULT true
);


-- 
-- Contains the main character information.
-- 

CREATE TABLE csbt_character_table (
	character_id serial NOT NULL PRIMARY KEY,
	uid integer NOT NULL REFERENCES cs_authentication_table(uid),
	character_name text,
	campaign_id integer DEFAULT NULL REFERENCES csbt_campaign_table(campaign_id),
	name text DEFAULT 'set character name...',
	eye_color varchar(20),
	height varchar(10),
	hair_color text,
	weight integer,
	age integer,
	sex varchar(3),
	race text,
	picture text --NOTE::: this could be either a URL or the encoded contents of the image...
);

CREATE TABLE csbt_character_attribute_table (
	character_ability_id serial NOT NULL PRIMARY KEY,
	character_id integer NOT NULL REFERENCES csbt_character_table(character_id),
	str integer NOT NULL DEFAULT 10,
	con integer NOT NULL DEFAULT 10,
	dex integer NOT NULL DEFAULT 10,
	'int' integer NOT NULL DEFAULT 10,
	wis integer NOT NULL DEFAULT 10,
	cha integer NOT NULL DEFAULT 10
);

CREATE TABLE csbt_skill_table (
	skill_id serial NOT NULL PRIMARY KEY,
	name text NOT NULL,
	ability varchar(3) NOT NULL,
	is_default bool NOT NULL DEFAULT FALSE
);

CREATE TABLE csbt_character_skill_table (
	character_skill_id serial NOT NULL PRIMARY KEY,
	character_id integer NOT NULL REFERENCES csbt_character_table(character_id),
	skill_id integer NOT NULL REFERENCES csbt_skill_table(skill_id),
	ranks integer NOT NULL DEFAULT 0
);

CREATE TABLE csbt_class_table (
	class_id serial NOT NULL PRIMARY KEY,
	name text NOT NULL,
	description text NOT NULL,
	level_adjustment integer NOT NULL DEFAULT 0,
	hit_dice varchar(20) NOT NULL,
	skill_points_per_level integer NOT NULL,
	alignment text,
);


CREATE TABLE csbt_character_attribute_table (
	character_attribute_id serial NOT NULL PRIMARY KEY,
	character_id integer NOT NULL REFERENCES csbt_character_table(character_id),
	attribute_type text NOT NULL,
	attribute_subtype text NOT NULL,
	attribute_name text NOT NULL,
	attribute_value text NOT NULL
);

/*
 * A note type, subtype, and name prefixes ("_" and "__")
 * 		A single underscore stands for an item that can be generated by addition
 * 		A double underscore stands for an item that could later be removed (i.e. "shield" could be removed; the "armor" 
 * 			value would actually be a combined value of all the "ac" values of all protective items)
 *
 *  id	||  type		|| subtype				|| name			|| value
 * -----++--------------++----------------------++--------------++---------------
 *     	|| skill		|| knowledge nature		|| _total		|| 3
 *     	|| skill		|| knowledge nature		|| _abilityname	|| int
 *     	|| skill		|| knowledge nature		|| __abilitymod	|| 1
 * 		|| skill		|| knowledge nature		|| ranks		|| 2
 * 		|| skill		|| knowledge nature		|| misc_mod		|| 0
 *     	|| skill		|| appraise				|| _total		|| 3
 *     	|| skill		|| appraise				|| _abilityname	|| wis
 *     	|| skill		|| appraise				|| __abilitymod	|| 1
 * 		|| skill		|| appraise				|| ranks		|| 2
 * 		|| skill		|| appraise				|| misc_mod		|| 0
 * 		|| ability		|| str					|| _total		|| 16
 * 		|| ability		|| str					|| _bonus		|| 3
 * 		|| ability		|| str					|| temp_total	|| (null)
 * 		|| ability		|| str					|| _temp_bonus	|| (null)
 * 		|| ac			|| _total				|| (null)		|| 15
 * 		|| ac			|| _base				|| (null)		|| 10
 * 		|| ac			|| _armor				|| (null)		|| 2
 * 		|| ac			|| __shield				|| (null)		|| 0
 * 		|| ac			|| _dex					|| (null)		|| 3
 * 		|| ac			|| _size				|| (null)		|| 0
 * 		|| weaponslot	|| name					|| (null)		|| greatsword
 * 		|| weaponslot	|| total_atk_bonus		|| (null)		|| +3
 * 		|| weaponslot	|| damage				|| (null)		|| 2d6+4
 * 		|| weaponslot	|| critical				|| (null)		|| x2
 * 		|| weaponslot	|| range				|| (null)		|| (null)
 * 		|| weaponslot	|| special_properties	|| (null)		|| (null)
 * 		|| weaponslot	|| ammunition			|| (null)		|| (null)
 * 		|| weaponslot	|| weight				|| (null)		|| (null)
 * 		|| weaponslot	|| size					|| (null)		|| medium
 * 		|| weaponslot	|| type					|| (null)		|| slashing
 */